# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d15754a220d59e11eed211b0ffe2e042d2b6da53fe3bc5e9c4b58c592619167ae27f46b625dca2529fe43f0da343018debb7e80bbed84f9203a3a989e53b8f4c

test:
  secret_key_base: 3e74554583b623a0900f3df25cb21424504384249c6e07acea3f4af02a080b92fa8ab3d5ae0e969f567f68fc3a636c5dbbb0eee320fe57f23d96aa8757e245e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
